### ISSUE TITLE
Mame-rr do not compile in Windows 10 with Mingw-mame build 

### ISSUE THREAD

**Issue by francoisadt** [TASVideos/mame-rr#11]
Mame-rr does compile "out-of-the-box"
Please advise what is the problem. Both mame gcc and mame vs2017 gave the same error.

Pull latest source
Set command in mingw (mame tools build version) to config64
execute both mame gcc build and vs2017 build. Both gave same error. 

MAME VS2017 BUILD:
make MSVC_BUILD=1 DEBUG=1 SYMBOLS=1 TARGET=mame REGENIE=1 TOOLS=1 SUBTARGET=mame NOWERROR=1 -j5

MAME GCC BUILD:
make DEBUG=1 SYMBOLS=1

Error:
[MINGW64] C:\DevTools\mamebuildenv\msys64\src\mame-rr-0.1-beta\mame-rr>make DEBUG=1 SYMBOLS=1
Compiling src/osd/windows/winwork.c...
src/osd/windows/winwork.c: In function 'void* compare_exchange_ptr(void* volatile*, void*, void*)':
src/osd/windows/winwork.c:204:63: error: cast from 'void*' to 'LONG {aka long int}' loses precision [-fpermissive]
  INT32 result = InterlockedCompareExchange((LPLONG)ptr, (LONG)exchange, (LONG)compare);
                                                               ^~~~~~~~
src/osd/windows/winwork.c:204:79: error: cast from 'void*' to 'LONG {aka long int}' loses precision [-fpermissive]
  INT32 result = InterlockedCompareExchange((LPLONG)ptr, (LONG)exchange, (LONG)compare);
                                                                               ^~~~~~~
src/osd/windows/winwork.c:205:17: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  return (void *)result;
                 ^~~~~~
makefile:720: recipe for target 'obj/windows/mamed/osd/windows/winwork.o' failed
make: *** [obj/windows/mamed/osd/windows/winwork.o] Error 1

from path:
C:\DevTools\mamebuildenv\msys64\src\mame-rr-0.1-beta\mame-rr

mingw vars and paths set:
[MINGW64] C:\DevTools\mamebuildenv\msys64\src\mame-rr-0.1-beta\mame-rr>path                                             PATH=;C:\DevTools\mamebuildenv\msys64;C:\DevTools\mamebuildenv\msys64\win32;C:\DevTools\mamebuildenv\msys64\mingw64\bin;C:\DevTools\mamebuildenv\msys64\usr\bin;"C:\DevTools\mamebuildenv\msys64\win32;C:\DevTools\mamebuildenv\msys64\win32;C:\DevTools\mamebuildenv\msys64;C:\DevTools\mamebuildenv\msys64\mingw64\bin;C:\DevTools\mamebuildenv\msys64\mingw64\x86_64-w64-mingw32\bin;";C:\Devtools\Python\Python37\Scripts\;C:\Devtools\Python\Python37\;C:\DevTools\mamebuildenv\msys64;"C:\DevTools\mamebuildenv\msys64\win32;C:\DevTools\mamebuildenv\msys64\mingw64\bin;C:\DevTools\mamebuildenv\msys64\usr\bin";C:\Microsoft\Microsoft Visual Studio\Shared\Anaconda3_64;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Microsoft MPI\Bin\;c:\Program Files (x86)\Nice Systems\NICE Player Codec Pack\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;c:\Program Files (x86)\NICE Systems\NICE Player Release 6\\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\IncrediBuild;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Lua\5.1;C:\Program Files (x86)\Lua\5.1\clibs;C:\Users\nb180957\AppData\Local\Microsoft\WindowsApps

**Comment by vadosnaprimer** [comment]
I have no idea what you're trying to do, this project only builds from branch 0.139, and with commands I put into readme.
