### ISSUE TITLE
Port Lua scripts for MAME

### ISSUE THREAD

**Issue by douglaslassance** [TASVideos/mame-rr#13]
This is more of a question than an issue. Did anyone port these Lua scripts for the official MAME?
The fact that you can run a script using `mame <rom_name> -autoboot_script <lua_script_filename>` makes me naively hopeful that it would be possible. Currently running them will raise errors such as `[LUA ERROR] in run: .\lua\garou-hitboxes.lua:37: attempt to index a nil value (global 'memory')`.

**Comment by vadosnaprimer** [comment]
MAME's luaengine is completely different. I don't know if anyone tried porting the rr fork scripts but maybe you'll find some on google.
