### ISSUE TITLE
Crash when replaying movie with input display script

### ISSUE THREAD

**Issue by xy2iii** [TASVideos/mame-rr#6]
1. Open any rom.
2. Open a lua console, and run the included input-display.lua script.
3. Replay a movie file.

Expected behavior: The movie should play from beginning with the input-display script running. (behavior in 0.139)
Actual behavior: MAME-RR crashes with "Fatal error: Input ports cannot be read at init time! (src/emu/inptport.c:1527)"

**Comment by vadosnaprimer** [comment]
Works just fine for me. Fresh unzip, loading a game, then the script, then recording a movie and then replaying it - all without stopping the script.
